
default: &default
  adapter: postgresql
  user: shop
  password: shop
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: shop_development
  
test:
  <<: *default
  database: shop_test

production:
  <<: *default
  database: shop_production
